services:
  backend:
    build:
      context: ./backend
    container_name: cc-api-backend
    image: cc-api-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      - db
      - cache
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cc-network

  db:
    image: postgres:latest
    container_name: cc-db
    environment:
      POSTGRES_USER: cc-user
      POSTGRES_PASSWORD: cc-password
      POSTGRES_DB: cc
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cc-network

  cache:
    image: redis:7
    container_name: cc-cache
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - cc-network

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/postgres_data

  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/redis_data

networks:
  cc-network:
    driver: bridge
